=== aajn88/MinerPCAdviser/MPCA_SentimentAnalysisModule/data/classifiers/trainingAndTestFormat.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/trainingAndTestFormat.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE traningAndTest SYSTEM "trainingAndTestFormat.dtd">

    <traningAndTest>
    ...
    </traningAndTest>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT traningAndTest (tests|classifiers|datasets)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datasets (dataset)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dataset (query)*>
<!ATTLIST dataset
    ref CDATA #IMPLIED
    details CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT query (#PCDATA)>
<!ATTLIST query
    offset CDATA #IMPLIED
    maxResults CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT classifiers (classifier)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT classifier (category)*>
<!ATTLIST classifier
    ref CDATA #IMPLIED
    class (dataProcessing.sentimentAnalysis.MpcaLingPipeClassifier) #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT category (dataset)+>
<!ATTLIST category
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tests (test)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT test (classifier,expectedCategory+)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT expectedCategory (dataset)+>
<!ATTLIST expectedCategory
    name CDATA #IMPLIED
  >

=== aajn88/MinerPCAdviser/MPCA_SentimentAnalysisModule/data/classifiers/trainingAndTest.xml
<!DOCTYPE traningAndTest SYSTEM "trainingAndTestFormat.dtd">
<traningAndTest>
    <datasets>			
		<!-- POSITIVE -->
		<dataset id = "newEggPositive" details = "Polaridad Positiva de newegg">
			<query>
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'polarity' AND ca.value = 'POSITIVE'
			</query>
		</dataset>
		
		<dataset id = "5Estrellas" details = "5 estrellas sin newEgg">
			<query maxResults = "1000">
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaComment.pageId.pageId != 2 AND ca.mpcaAdditionType.addType = 'rank' AND ca.value = '5.0'
			</query>
		</dataset>
		<!-- NEUTRAL
		<dataset id = "newEggNeutral" details = "Polaridad neutral de newegg">
			<query>
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaComment.pageId.pageId = 2 AND ca.mpcaAdditionType.addType = 'polarity' AND ca.value = 'NEUTRAL'
			</query>
		</dataset>
		-->
		<!-- NEGATIVE -->
		<dataset id = "1y2Estrellas" details = "Rank de 1 y 2 estrellas sin newEgg">
			<query maxResults = "1000">
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaComment.pageId.pageId != 2 AND ca.mpcaAdditionType.addType = 'rank' AND (ca.value = '1.0' OR ca.value = '2.0')
			</query>
		</dataset>
		
		<dataset id = "newEggNegative" details = "Polaridad Negativa de newegg">
			<query>
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'polarity' AND ca.value = 'NEGATIVE'
			</query>
		</dataset>
		
		<!-- TEST DATA SETS -->
		
		<dataset id = "5Estrellas - test" details = "5 estrellas">
			<query>
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND ca.value = '5.0'
			</query>
		</dataset>
		<!--
		<dataset id = "3Estrellas - test" details = "Rank de 3 estrellas">
			<query>
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND (ca.value = '3.0')
			</query>
		</dataset>
		-->
		<dataset id = "1y2Estrellas - test" details = "Rank de 1 y 2 estrellas">
			<query>
				SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND (ca.value = '1.0' OR ca.value = '2.0')
			</query>
		</dataset>
    </datasets>
    <classifiers>
        <classifier id = "lingPipeClassifier2" class = "dataProcessing.sentimentAnalysis.MpcaLingPipeClassifier">
			<category name = "POSITIVE">
				<dataset ref="newEggPositive"/>
				<dataset ref="5Estrellas"/>
            </category>
			<!--
            <category name = "NEUTRAL">
                <dataset ref="newEggNeutral"/>
            </category>
			-->
			<category name = "NEGATIVE">
                <dataset ref="1y2Estrellas"/>
				<dataset ref="newEggNegative"/>
            </category>
        </classifier>
    </classifiers>
    <tests>
        <test>
            <classifier ref = "lingPipeClassifier2"/>
            <expectedCategory name = "POSITIVE">
				<dataset ref="5Estrellas - test"/>
            </expectedCategory>
			<!--
            <expectedCategory name = "NEUTRAL">
                <dataset ref="3Estrellas - test"/>
            </expectedCategory>
			-->
			<expectedCategory name = "NEGATIVE">
                <dataset ref="1y2Estrellas - test"/>
            </expectedCategory>
        </test>
    </tests>
</traningAndTest>

=== aajn88/MinerPCAdviser/MPCA_SentimentAnalysisModule/data/classifiers/trainingAndTest - HostedGoogle.xml
<!DOCTYPE traningAndTest SYSTEM "trainingAndTestFormat.dtd">
<traningAndTest>
    <datasets>
            <!--dataset id = "dataSet0" details = "Todos los comentarios">
                <query>
                    SELECT cc FROM MpcaComment cc
                </query>
            </dataset>
            <dataset id = "dataSet1" details = "Rank de 5 estrellas (maxResults = 1000)">
                <query maxResults = "1000">
                    SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND ca.value = '5.0'
                </query>
            </dataset>
            <dataset id = "dataSet2" details = "Rank de 1 y 2 estrellas (maxResults = 1000)">
                <query maxResults = "1000">
                    SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND (ca.value = '1.0' OR ca.value = '2.0')
                </query>
            </dataset>
            <dataset id = "dataSet3" details = "Rank de 4 y 5 estrellas (maxResults = 100)">
                <query offset = "100">
                    SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND (ca.value = '4.0' OR ca.value = '5.0')
                </query>
            </dataset-->
            <dataset id = "dataSet4" details = "Polaridad Positiva">
                <query>
                    SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'polarity' AND ca.value = 'POSITIVE'
                </query>
            </dataset>
            <dataset id = "dataSet5" details = "Polaridad Negativa">
                <query>
                    SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'polarity' AND ca.value = 'NEGATIVE'
                </query>
            </dataset>
            <!--dataset id = "dataSet6" details = "Rank de 4 y 5 estrellas">
                <query>
                    SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND (ca.value = '4.0' OR ca.value = '5.0')
                </query>
            </dataset>
            <dataset id = "dataSet7" details = "Rank de 1 y 2 estrellas">
                <query>
                    SELECT ca.mpcaComment FROM MpcaCommentAddition ca WHERE ca.mpcaAdditionType.addType = 'rank' AND (ca.value = '1.0' OR ca.value = '2.0')
                </query>
            </dataset-->
    </datasets>
    <classifiers>
        <!--classifier id = "classifier1" class = "dataProcessing.sentimentAnalysis.MpcaLingPipeClassifier">
            <category name = "POSITIVE">
                <dataset ref="dataSet1"/>
            </category>
            <category name = "NEGATIVE">
                <dataset ref="dataSet2"/>
            </category>
        </classifier-->
        <classifier id = "googleClassifier" class = "dataProcessing.sentimentAnalysis.MpcaGoogleClassifier">
        </classifier>
    </classifiers>
    <tests>
        <!--test>
            <classifier ref = "classifier1"/>
            <expectedCategory name = "POSITIVE">
                <dataset ref = "dataSet4"/>
            </expectedCategory>
            <expectedCategory name = "NEGATIVE">
                <dataset ref = "dataSet5"/>
            </expectedCategory>
        </test-->
        <test>
            <classifier ref = "googleClassifier"/>
            <expectedCategory name = "POSITIVE">
                <dataset ref = "dataSet4"/>
            </expectedCategory>
            <expectedCategory name = "NEGATIVE">
                <dataset ref = "dataSet5"/>
            </expectedCategory>
        </test>
        <!--test>
            <classifier ref = "classifier2"/>
            <expectedCategory name = "POSITIVE">
                <dataset ref = "dataSet6"/>
            </expectedCategory>
            <expectedCategory name = "NEGATIVE">
                <dataset ref = "dataSet7"/>
            </expectedCategory>
        </test-->
    </tests>
</traningAndTest>
